CREATE TABLE PLAN_MONTH(
    ID BIGSERIAL PRIMARY KEY,
    REFERENCE_MONTH INT NOT NULL,
    REFERENCE_YEAR INT NOT NULL,
    TOTAL_EXPENSES DECIMAL,
    TOTAL_INCOME DECIMAL,
    GOAL DECIMAL,
    SURPLUS DECIMAL
);

CREATE TABLE INCOME(
    ID BIGSERIAL PRIMARY KEY,
    PLAN_MONTH_ID BIGINT NOT NULL,
    DESCRIPTION CHAR(255) NOT NULL,
    INCOME_VALUE DECIMAL NOT NULL,
    FOREIGN KEY (PLAN_MONTH_ID) references PLAN_MONTH(ID)
);

CREATE TABLE EXPENSE(
    ID BIGSERIAL PRIMARY KEY,
    PLAN_MONTH_ID BIGINT NOT NULL,
    DESCRIPTION CHAR(255) NOT NULL,
    EXPENSE_VALUE DECIMAL NOT NULL,
    REFUND BOOLEAN NOT NULL,
    INSTALLMENT INT,
    TOTAL_INSTALLMENTS INT,
    RECEIPT_FILE CHAR(255),
    RECEIPT_FILE_UPLOADED BOOLEAN NOT NULL,
    FOREIGN KEY (PLAN_MONTH_ID) references PLAN_MONTH(ID)
);
